services:
  - type: web
    name: ContextClosest
    env: python
    region: ohio
    plan: free
    buildCommand: "pip install -r requirements-render.txt"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: RENDER
        value: "True"
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
